//! Quantum Key Distribution (QKD) Protocols
//!
//! This module provides implementations of quantum key distribution protocols:
//! - BB84 protocol (first and most famous QKD protocol)
//! - E91 protocol (entanglement-based QKD)
//! - Decoy state QKD (practical implementation with weak coherent pulses)
//! - Key sifting and error reconciliation
//! - Security analysis and authentication

use crate::quantum::{QuantumState, QuantumGate, QuantumError, QuantumResult};

use alloc::vec::Vec;
use alloc::string::String;
use alloc::format;

// Define PI constant
const PI: f64 = 3.14159265358979323846;

/// Trait for QKD protocols
pub trait QKDProtocol {
    /// Get the name of the protocol
    fn name(&self) -> &str;

    /// Generate a raw quantum key using the protocol
    fn generate_key(&self, key_length: usize) -> QuantumResult<QuantumKey>;

    /// Calculate the estimated secret key rate
    fn key_rate(&self, error_rate: f64) -> f64;

    /// Get the security parameters
    fn security_parameters(&self) -> SecurityParameters;
}

/// Security parameters for QKD
#[derive(Debug, Clone)]
pub struct SecurityParameters {
    /// Bit error rate threshold
    pub error_threshold: f64,
    /// Minimum required bits for privacy amplification
    pub min_privacy_bits: usize,
    /// Whether information-theoretic security is proven
    pub proven_secure: bool,
    /// Estimated security level (bits of security)
    pub security_level: usize,
}

/// Quantum key generated by QKD
#[derive(Debug, Clone)]
pub struct QuantumKey {
    /// The raw key bits
    pub bits: Vec<bool>,
    /// Basis choices for each bit
    pub bases: Vec<Basis>,
    /// Error rate estimate
    pub error_rate: f64,
    /// Length of the key
    pub length: usize,
}

impl QuantumKey {
    /// Create a new quantum key
    pub fn new(bits: Vec<bool>, bases: Vec<Basis>) -> Self {
        let length = bits.len();
        Self {
            bits,
            bases,
            error_rate: 0.0,
            length,
        }
    }

    /// Convert key to bytes
    pub fn to_bytes(&self) -> Vec<u8> {
        self.bits.chunks(8)
            .map(|chunk| {
                chunk.iter()
                    .enumerate()
                    .fold(0u8, |acc, (i, &bit)| {
                        acc | ((bit as u8) << i)
                    })
            })
            .collect()
    }

    /// Get the key as a hex string
    pub fn to_hex(&self) -> String {
        self.to_bytes()
            .iter()
            .map(|b| format!("{:02x}", b))
            .collect()
    }

    /// Estimate the quantum bit error rate (QBER)
    pub fn estimate_error_rate(&self, expected: &QuantumKey) -> f64 {
        if self.length != expected.length {
            return 1.0;
        }

        let mut errors = 0;
        for (a, b) in self.bits.iter().zip(expected.bits.iter()) {
            if a != b {
                errors += 1;
            }
        }

        errors as f64 / self.length as f64
    }
}

/// Measurement basis in QKD protocols
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Basis {
    /// Rectilinear basis (Z basis: |0⟩, |1⟩)
    Rectilinear,
    /// Diagonal basis (X basis: |+⟩, |-⟩)
    Diagonal,
}

impl Basis {
    /// Get a random basis
    pub fn random() -> Self {
        if rand::random() {
            Basis::Rectilinear
        } else {
            Basis::Diagonal
        }
    }

    /// Measure a qubit in this basis
    pub fn measure(&self, state: &mut QuantumState, qubit: usize) -> QuantumResult<bool> {
        match self {
            Basis::Rectilinear => {
                // Z-basis measurement
                let prob_1 = state.get_probability(1u64 << qubit)?;
                Ok(rand::random::<f64>() < prob_1)
            }
            Basis::Diagonal => {
                // X-basis measurement
                state.apply_single_qubit_gate(&QuantumGate::h(), qubit)?;
                let prob_1 = state.get_probability(1u64 << qubit)?;
                Ok(rand::random::<f64>() < prob_1)
            }
        }
    }

    /// Prepare a qubit in this basis
    pub fn prepare(&self, state: &mut QuantumState, qubit: usize, bit: bool) -> QuantumResult<()> {
        match self {
            Basis::Rectilinear => {
                // Prepare |0⟩ or |1⟩
                if bit {
                    state.apply_single_qubit_gate(&QuantumGate::x(), qubit)?;
                }
            }
            Basis::Diagonal => {
                // Prepare |+⟩ or |-⟩
                state.apply_single_qubit_gate(&QuantumGate::h(), qubit)?;
                if bit {
                    state.apply_single_qubit_gate(&QuantumGate::z(), qubit)?;
                }
            }
        }
        Ok(())
    }
}

/// BB84 Protocol - First QKD Protocol
///
/// Proposed by Bennett and Brassard in 1984.
/// Uses two conjugate bases (rectilinear and diagonal).
#[derive(Debug, Clone)]
pub struct BB84Protocol {
    /// Number of bits to generate
    key_length: usize,
    /// Estimated quantum bit error rate
    qber: f64,
}

impl BB84Protocol {
    /// Create a new BB84 protocol instance
    pub fn new(key_length: usize) -> Self {
        Self {
            key_length,
            qber: 0.0,
        }
    }

    /// Alice's side: prepare and send qubits
    pub fn alice_prepare(&self) -> QuantumResult<(Vec<QuantumState>, Vec<Basis>, Vec<bool>)> {
        let mut qubits = Vec::new();
        let mut bases = Vec::new();
        let mut bits = Vec::new();

        for _ in 0..self.key_length {
            let mut state = QuantumState::new(1)?;
            let basis = Basis::random();
            let bit: bool = rand::random();

            basis.prepare(&mut state, 0, bit)?;

            qubits.push(state);
            bases.push(basis);
            bits.push(bit);
        }

        Ok((qubits, bases, bits))
    }

    /// Bob's side: measure received qubits
    pub fn bob_measure(&self, qubits: &[QuantumState]) -> QuantumResult<(Vec<Basis>, Vec<bool>)> {
        let mut bases = Vec::new();
        let mut bits = Vec::new();

        for qubit in qubits {
            let mut state = qubit.clone();
            let basis = Basis::random();
            let bit = basis.measure(&mut state, 0)?;

            bases.push(basis);
            bits.push(bit);
        }

        Ok((bases, bits))
    }

    /// Sift the key: keep only bits where bases match
    pub fn sift_keys(
        &self,
        alice_bases: &[Basis],
        bob_bases: &[Basis],
        alice_bits: &[bool],
        bob_bits: &[bool],
    ) -> QuantumResult<KeySifting> {
        if alice_bases.len() != bob_bases.len() || alice_bits.len() != bob_bits.len() {
            return Err(QuantumError::InvalidQubitCount(0));
        }

        let mut sifted_alice = Vec::new();
        let mut sifted_bob = Vec::new();
        let mut matching_indices = Vec::new();

        for (i, (a_basis, b_basis)) in alice_bases.iter().zip(bob_bases.iter()).enumerate() {
            if a_basis == b_basis {
                sifted_alice.push(alice_bits[i]);
                sifted_bob.push(bob_bits[i]);
                matching_indices.push(i);
            }
        }

        Ok(KeySifting {
            sifted_key_alice: sifted_alice,
            sifted_key_bob: sifted_bob,
            matching_indices: matching_indices.clone(),
            sifting_efficiency: matching_indices.len() as f64 / alice_bases.len() as f64,
        })
    }

    /// Estimate quantum bit error rate
    pub fn estimate_qber(&self, alice_bits: &[bool], bob_bits: &[bool]) -> f64 {
        if alice_bits.len() != bob_bits.len() {
            return 1.0;
        }

        let mut errors = 0;
        for (a, b) in alice_bits.iter().zip(bob_bits.iter()) {
            if a != b {
                errors += 1;
            }
        }

        errors as f64 / alice_bits.len() as f64
    }
}

impl QKDProtocol for BB84Protocol {
    fn name(&self) -> &str {
        "BB84 Protocol"
    }

    fn generate_key(&self, key_length: usize) -> QuantumResult<QuantumKey> {
        let protocol = BB84Protocol::new(key_length);

        // Alice prepares qubits
        let (qubits, alice_bases, alice_bits) = protocol.alice_prepare()?;

        // Bob measures qubits
        let (bob_bases, bob_bits) = protocol.bob_measure(&qubits)?;

        // Sift keys
        let sifting = protocol.sift_keys(&alice_bases, &bob_bases, &alice_bits, &bob_bits)?;

        // Estimate QBER
        let qber = protocol.estimate_qber(&sifting.sifted_key_alice, &sifting.sifted_key_bob);
        let key_len = sifting.sifted_key_alice.len();

        Ok(QuantumKey {
            bits: sifting.sifted_key_alice,
            bases: alice_bases,
            error_rate: qber,
            length: key_len,
        })
    }

    fn key_rate(&self, error_rate: f64) -> f64 {
        // BB84 key rate with one-way post-processing
        // R = 1 - 2*h(QBER) where h is binary entropy
        if error_rate > 0.11 {
            return 0.0; // Above threshold
        }

        let h = -(error_rate * error_rate.log2() + (1.0 - error_rate) * (1.0 - error_rate).log2());
        1.0 - 2.0 * h
    }

    fn security_parameters(&self) -> SecurityParameters {
        SecurityParameters {
            error_threshold: 0.11, // 11% QBER threshold
            min_privacy_bits: 100,
            proven_secure: true,
            security_level: 128, // Can provide 128-bit security
        }
    }
}

/// Key sifting results
#[derive(Debug, Clone)]
pub struct KeySifting {
    /// Sifted key from Alice's perspective
    pub sifted_key_alice: Vec<bool>,
    /// Sifted key from Bob's perspective
    pub sifted_key_bob: Vec<bool>,
    /// Indices where bases matched
    pub matching_indices: Vec<usize>,
    /// Sifting efficiency
    pub sifting_efficiency: f64,
}

/// E91 Protocol - Entanglement-based QKD
///
/// Proposed by Ekert in 1991.
/// Uses quantum entanglement and Bell's theorem for security.
#[derive(Debug, Clone)]
pub struct E91Protocol {
    /// Number of Bell pairs to generate
    num_pairs: usize,
}

impl E91Protocol {
    /// Create a new E91 protocol instance
    pub fn new(num_pairs: usize) -> Self {
        Self { num_pairs }
    }

    /// Generate Bell pairs
    pub fn generate_bell_pairs(&self) -> QuantumResult<Vec<QuantumState>> {
        let mut pairs = Vec::new();

        for _ in 0..self.num_pairs {
            // Create Bell state |Φ+⟩ = (|00⟩ + |11⟩)/√2
            let mut state = QuantumState::new(2)?;
            state.apply_single_qubit_gate(&QuantumGate::h(), 0)?;
            state.apply_two_qubit_gate(&crate::quantum::TwoQubitGate::cnot(), 0, 1)?;
            pairs.push(state);
        }

        Ok(pairs)
    }

    /// Alice's measurement settings (3 bases)
    pub fn alice_measure(&self, state: &mut QuantumState, setting: usize) -> QuantumResult<bool> {
        if setting >= 3 {
            return Err(QuantumError::QubitIndexOutOfBounds(setting));
        }

        // Alice's measurement angles: 0°, 45°, 90°
        let angles = [0.0, PI / 4.0, PI / 2.0];
        let angle = angles[setting];

        // Rotate measurement basis
        state.apply_single_qubit_gate(&QuantumGate::ry(angle), 0)?;
        state.apply_single_qubit_gate(&QuantumGate::h(), 0)?;

        let prob_1 = state.get_probability(1u64 << 0)?;
        Ok(rand::random::<f64>() < prob_1)
    }

    /// Bob's measurement settings (3 bases)
    pub fn bob_measure(&self, state: &mut QuantumState, setting: usize) -> QuantumResult<bool> {
        if setting >= 3 {
            return Err(QuantumError::QubitIndexOutOfBounds(setting));
        }

        // Bob's measurement angles: 45°, 90°, 135°
        let angles = [PI / 4.0, PI / 2.0, 3.0 * PI / 4.0];
        let angle = angles[setting];

        // Rotate measurement basis
        state.apply_single_qubit_gate(&QuantumGate::ry(angle), 1)?;
        state.apply_single_qubit_gate(&QuantumGate::h(), 1)?;

        let prob_1 = state.get_probability(1u64 << 1)?;
        Ok(rand::random::<f64>() < prob_1)
    }

    /// Calculate CHSH inequality violation
    pub fn chsh_value(&self, correlations: &[f64]) -> f64 {
        if correlations.len() < 4 {
            return 0.0;
        }

        // CHSH value: S = E(a0b0) + E(a0b1) + E(a1b0) - E(a1b1)
        // Classical bound: |S| ≤ 2
        // Quantum bound: |S| ≤ 2√2 ≈ 2.828
        correlations[0] + correlations[1] + correlations[2] - correlations[3]
    }
}

impl QKDProtocol for E91Protocol {
    fn name(&self) -> &str {
        "E91 Protocol (Ekert 1991)"
    }

    fn generate_key(&self, key_length: usize) -> QuantumResult<QuantumKey> {
        let protocol = E91Protocol::new(key_length);
        let mut bits = Vec::new();
        let mut bases = Vec::new();

        let pairs = protocol.generate_bell_pairs()?;

        for mut state in pairs {
            let alice_setting = rand::random::<usize>() % 3;
            let bob_setting = rand::random::<usize>() % 3;

            let alice_bit = protocol.alice_measure(&mut state, alice_setting)?;
            let _bob_bit = protocol.bob_measure(&mut state, bob_setting)?;

            // Keep bits when settings match
            if alice_setting == bob_setting {
                bits.push(alice_bit);
                bases.push(Basis::Rectilinear); // Placeholder
            }
        }

        let key_len = bits.len();
        Ok(QuantumKey {
            bits,
            bases,
            error_rate: 0.0,
            length: key_len,
        })
    }

    fn key_rate(&self, error_rate: f64) -> f64 {
        // E91 key rate depends on entanglement quality
        if error_rate > 0.07 {
            return 0.0;
        }
        0.75 * (1.0 - error_rate)
    }

    fn security_parameters(&self) -> SecurityParameters {
        SecurityParameters {
            error_threshold: 0.07, // 7% error threshold
            min_privacy_bits: 80,
            proven_secure: true,
            security_level: 256, // Information-theoretic security
        }
    }
}

/// Decoy State Protocol
///
/// Practical implementation of BB84 using weak coherent pulses
/// instead of single photons. Uses decoy states to detect photon number
/// splitting attacks.
#[derive(Debug, Clone)]
pub struct DecoyStateProtocol {
    /// Mean photon number for signal states
    mu_signal: f64,
    /// Mean photon number for decoy states
    mu_decoy: f64,
    /// Probability of vacuum state
    prob_vacuum: f64,
}

impl DecoyStateProtocol {
    /// Create a new decoy state protocol
    pub fn new() -> Self {
        Self {
            mu_signal: 0.5,
            mu_decoy: 0.1,
            prob_vacuum: 0.1,
        }
    }

    /// Generate weak coherent pulse
    pub fn generate_wcp(&self, intensity: f64) -> QuantumResult<QuantumState> {
        // Sample from Poisson distribution
        let k = Self::poisson_sample(intensity);

        if k == 0 {
            // Vacuum state
            Ok(QuantumState::new(1)?)
        } else if k == 1 {
            // Single photon
            let mut state = QuantumState::new(1)?;
            let basis = Basis::random();
            let bit: bool = rand::random();
            basis.prepare(&mut state, 0, bit)?;
            Ok(state)
        } else {
            // Multi-photon state (insecure)
            Ok(QuantumState::new(1)?)
        }
    }

    /// Sample from Poisson distribution
    fn poisson_sample(lambda: f64) -> usize {
        let l = (-lambda).exp();
        let mut k = 0usize;
        let mut p = 1.0;

        while p > l {
            k += 1;
            p *= rand::random::<f64>();
        }

        k - 1
    }

    /// Estimate single-photon contribution
    pub fn estimate_single_photon_yield(&self) -> f64 {
        // Simplified estimation
        // In practice, would use decoy state statistics
        0.1
    }
}

impl Default for DecoyStateProtocol {
    fn default() -> Self {
        Self::new()
    }
}

impl QKDProtocol for DecoyStateProtocol {
    fn name(&self) -> &str {
        "Decoy State BB84"
    }

    fn generate_key(&self, key_length: usize) -> QuantumResult<QuantumKey> {
        // Use BB84 protocol with decoy states
        let bb84 = BB84Protocol::new(key_length);
        bb84.generate_key(key_length)
    }

    fn key_rate(&self, error_rate: f64) -> f64 {
        // Decoy state improves distance and rate
        let single_photon_yield = self.estimate_single_photon_yield();
        single_photon_yield * (1.0 - 2.0 * error_rate.log2())
    }

    fn security_parameters(&self) -> SecurityParameters {
        SecurityParameters {
            error_threshold: 0.11,
            min_privacy_bits: 100,
            proven_secure: true,
            security_level: 128,
        }
    }
}

/// Error reconciliation for QKD
pub struct ErrorReconciliation;

impl ErrorReconciliation {
    /// Cascade error correction algorithm
    pub fn cascade(alice_key: &[bool], bob_key: &[bool]) -> QuantumResult<Vec<bool>> {
        if alice_key.len() != bob_key.len() {
            return Err(QuantumError::InvalidQubitCount(0));
        }

        let mut corrected_key = bob_key.to_vec();
        let mut block_size = alice_key.len() / 2;

        while block_size > 0 {
            // Compare parity of blocks
            for i in (0..alice_key.len()).step_by(block_size) {
                let end = (i + block_size).min(alice_key.len());
                let alice_parity = alice_key[i..end].iter().filter(|&&b| b).count() % 2;
                let bob_parity = corrected_key[i..end].iter().filter(|&&b| b).count() % 2;

                if alice_parity != bob_parity {
                    // Binary search within block to find error
                    Self::binary_search_correct(
                        &alice_key[i..end],
                        &mut corrected_key[i..end],
                    );
                }
            }

            block_size /= 2;
        }

        Ok(corrected_key)
    }

    /// Binary search and correct a single error
    fn binary_search_correct(alice_block: &[bool], bob_block: &mut [bool]) {
        let mut left = 0;
        let mut right = alice_block.len();

        while right - left > 1 {
            let mid = (left + right) / 2;
            let alice_parity = alice_block[left..mid].iter().filter(|&&b| b).count() % 2;
            let bob_parity = bob_block[left..mid].iter().filter(|&&b| b).count() % 2;

            if alice_parity == bob_parity {
                left = mid;
            } else {
                right = mid;
            }
        }

        // Flip the error bit
        bob_block[left] = !bob_block[left];
    }

    /// Privacy amplification using universal hashing
    pub fn privacy_amplify(key: &[bool], target_length: usize) -> Vec<bool> {
        // Simplified privacy amplification
        // In practice, would use universal hash functions

        let mut result = vec![false; target_length];
        for i in 0..target_length {
            let hash_index = (i * 7) % key.len();
            result[i] = key[hash_index];
        }

        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basis_random() {
        let basis = Basis::random();
        assert!(matches!(basis, Basis::Rectilinear | Basis::Diagonal));
    }

    #[test]
    fn test_bb84_protocol() {
        let protocol = BB84Protocol::new(100);
        let key = protocol.generate_key(100).unwrap();
        assert!(!key.bits.is_empty());
        assert!(key.length > 0);
    }

    #[test]
    fn test_key_sifting() {
        let protocol = BB84Protocol::new(100);

        let alice_bases = vec![Basis::Rectilinear, Basis::Diagonal, Basis::Rectilinear];
        let bob_bases = vec![Basis::Rectilinear, Basis::Rectilinear, Basis::Diagonal];
        let alice_bits = vec![true, false, true];
        let bob_bits = vec![true, true, false];

        let sifting = protocol.sift_keys(&alice_bases, &bob_bases, &alice_bits, &bob_bits).unwrap();

        // Only first index has matching bases
        assert_eq!(sifting.matching_indices.len(), 1);
        assert_eq!(sifting.sifted_key_alice[0], true);
        assert_eq!(sifting.sifted_key_bob[0], true);
    }

    #[test]
    fn test_e91_protocol() {
        let protocol = E91Protocol::new(10);
        let pairs = protocol.generate_bell_pairs().unwrap();
        assert_eq!(pairs.len(), 10);
    }

    #[test]
    fn test_error_reconciliation() {
        let alice_key = vec![true, false, true, false, true];
        let bob_key = vec![true, true, true, false, true]; // Error at index 1

        let corrected = ErrorReconciliation::cascade(&alice_key, &bob_key).unwrap();
        assert_eq!(corrected, alice_key);
    }

    #[test]
    fn test_privacy_amplification() {
        let key = vec![true; 100];
        let amplified = ErrorReconciliation::privacy_amplify(&key, 50);
        assert_eq!(amplified.len(), 50);
    }
}
